<?php

    function cipher_menu() {
        $items = array();
        $items['cipher'] = array(
            'title' => 'Shift Cipher',
            'type' => MENU_NORMAL_ITEM,
            'access callback' => TRUE,
            'page callback' => 'drupal_get_form',
            'page arguments' => array('cipher_form'),
    );

    $items['cipher_success_page'] = array(
        'title' => 'Welcome to the Cipher Zone',
        'page callback' => 'cipher_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
    }

    function cipher_form() {
        $form['user_value'] = array(
            '#title' => 'Shift Value',
            '#type' => 'textfield',
            '#description' => t('Please enter the number of places you want the cipher to shift the letters.'),
            '#element_validate' => array('element_validate_integer_positive'),
            '#required' => TRUE,
        );
        $form['user_direction'] = array(
            '#title' => 'Shift Direction',
            '#type' => 'textfield',
            '#description' => t('Please enter the direction you want the letters shifted.'),
            '#element_validate' => array('element_validate_direction'),
            '#required' => TRUE,
        );
        $form['user_phrase'] = array(
            '#title' => 'Phrase',
            '#type' => 'textfield',
            '#description' => t('Please enter the phrase you want cipher-ized.'),
            '#element_validate' => array('element_validate_all'),
            '#required' => TRUE,
        );
        $form['submit'] = array(
            '#type' => 'submit',
            '#value' => 'Go',
        );
        return $form;
    }

    function element_validate_direction($element) {
        if (!in_array($element['#value'], array('left', 'Left', 'LEFT', 'right', 'Right', 'RIGHT'))) {
            form_error($element, t('Direction must be either left or right'));
        }
    }

    function element_validate_all($element, &$form_state) {
        $pattern =  '/[^A-Za-z0-9^\'^\:^\,^\-^\!^\(^\)^\.^\?^\"^\;\s]/';
        $user_phrase_check = $form_state['values']['user_phrase'];
        if (preg_match_all($pattern, $user_phrase_check)) {
            form_set_error('user_phrase', 'Input must only consist of letters, numbers, spaces and punctuation!');
        }
    }

    function cipher_form_submit($form, &$form_state) {
        $user_value = $form_state['values']['user_value'];
        $user_direction = $form_state['values']['user_direction'];
        $user_phrase = $form_state['values']['user_phrase'];

        $alphabet = array('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l',
        'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z');

        $spaces = $form_state['values']['user_value'];
        $direction = $form_state['values']['user_direction'];
        $phrase = $form_state['values']['user_phrase'];
        $lower_phrase = strtolower($phrase);
        $split_phrase = str_split($lower_phrase);
        $output = '';

        if (in_array($direction, array('left', 'Left', 'LEFT'))) {
            $direction = -1;
        } else {
            $direction = 1;
        }

        foreach ($split_phrase as $character) {

            if (in_array($character, $alphabet)) {
                $location = array_search($character, $alphabet);
                $new_location = ($spaces * $direction) + $location;
                if ($new_location < 0) {
                    $new_location += 26;
                } elseif ($new_location > 25) {
                    $new_location -= 26;
                }
                $output .= $alphabet[$new_location];
            } else {
                $output .= $character;
            }
        }
        $_SESSION['cipher_output'] = $output;
        $form_state['redirect'] = 'cipher_success_page';
    }

    function cipher_success() {
        return '<p>'.$_SESSION['cipher_output'].'</p>';
      }
